import BannerCard from '@/components/molecules/card/BannerCard'
import PostCard from '@/components/molecules/card/PostCard'
import Link from 'next/link'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
export const metadata = {
   title: 'Home Page | MetaBlog',
   description: 'Generated by create next app',
}
const postsDirectory = path.join(process.cwd(), 'app/posts')

export default function Home() {
   const files = fs.readdirSync(postsDirectory)
   const posts = files
      .map((fileName) => {
         const fileContent = fs.readFileSync(
            path.join(postsDirectory, fileName),
            'utf-8'
         )

         const { data: frontMatter } = matter(fileContent)
         return {
            meta: frontMatter,
            slug: fileName.replace('.mdx', ''),
         }
      })
      .sort((a, b) => a.slug.localeCompare(b.slug))
   return (
      <>
         <main className="container mx-auto">
            <div className="relative flex py-5 items-center px-4">
               <div className="flex-grow border-t border-gray-400"></div>
               <div className="flex-shrink mx-16 text-3xl ale">
                  <div className="text-center">
                     BUFF VĂN CÙNG POWERPUFF GIRLS
                  </div>
                  <div className="text-center text-xs italic">
                     #vanhoc#2k6#thpt
                  </div>
               </div>
               <div className="flex-grow border-t border-gray-400"></div>
            </div>
            {/* <div className="flex-grow border-t border-gray-400 mt-4 mb-8"></div> */}

            <section>
               <BannerCard />
            </section>

            {/* Latest Post */}
            <section className="my-20">
               <h3 className="text-base-content font-bold text-2xl mb-8 font-work leading-8">
                  Latest Post
               </h3>
               <div className=" grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 transform ">
                  {posts.map((post, idx) => (
                     <Link href={`/mdx/${post.slug}`} passHref key={post.slug}>
                        <PostCard
                           key={idx}
                           title={post.meta.title}
                           description={post.meta.description}
                           date={post.meta.date}
                        />
                     </Link>
                  ))}
               </div>
               <div className="flex items-center justify-center w-full mt-8">
                  <Link
                     href={`/blog`}
                     className="btn btn-outline btn-secondary text-secondary-content/60 font-work font-medium text-base"
                  >
                     View All Post
                  </Link>
               </div>
            </section>

            {/* Advertisement Component */}
            {/* <section className="mb-24">
            <Advertisement />
         </section> */}
            <div className="py-2">
               {posts.map((blog) => (
                  <Link href={'/mdx/' + blog.slug} passHref key={blog.slug}>
                     <div className="py-2 flex justify-between align-middle gap-2">
                        <div>
                           <h3 className="text-lg font-blod">
                              {blog.meta.title}
                           </h3>
                           <div>
                              <p className="text-gray-400">
                                 {blog.meta.description}
                              </p>
                           </div>
                           <div className="my-auto text-gray-400">
                              <p>{blog.meta.date}</p>
                           </div>
                        </div>
                     </div>
                  </Link>
               ))}
            </div>
         </main>
      </>
   )
}
